markdown: kramdown
pygments: true
permalink: /posts/:title.html
auto: true
rdiscount:
  extensions: [smart]

title: 星爷的博客
author:
  name: 星爷
  email: longxingwei@gmail.com
  github: lxWei 

production_url: http://tech.readingnotes.site

baseurl: /

theme: jekyll-theme-architect
